name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - '**/*'
      - '!docs/**'
      - '!README.md'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.changed }}
      app_changed: ${{ steps.changes.outputs.app_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changes
        run: |
          echo changed=true | tee -a $GITHUB_OUTPUT
          echo app_changed=true | tee -a $GITHUB_OUTPUT

  linux-app-build:
    needs: [changes]
    if: needs.changes.outputs.app_changed == 'True'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libayatana-appindicator3-dev libgtk-3-dev libwebkit2gtk-4.1-dev libnotify-dev pkg-config
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install UI dependencies
        working-directory: ./app/ui/app
        run: npm ci
      - name: Build UI
        working-directory: ./app/ui/app
        run: npm run build
      - name: Install tscriptify
        run: |
          go install github.com/tkrajina/typescriptify-golang-structs/tscriptify@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run go generate
        run: go generate ./app/...
      - name: Build Linux app
        run: CGO_ENABLED=1 go build -o /dev/null ./app/cmd/app

  test:
    needs: [changes]
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install Linux app dependencies
        run: sudo apt-get update && sudo apt-get install -y libayatana-appindicator3-dev libgtk-3-dev libwebkit2gtk-4.1-dev libnotify-dev pkg-config
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install UI dependencies
        working-directory: ./app/ui/app
        run: npm ci
      - name: Install tscriptify
        run: |
          go install github.com/tkrajina/typescriptify-golang-structs/tscriptify@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Build UI
        working-directory: ./app/ui/app
        run: npm run build
      - name: Run UI tests
        working-directory: ./app/ui/app
        run: npm test
      - name: Run go generate
        run: go generate ./app/...
      - name: go test app and ui
        if: always()
        run: go test -count=1 -benchtime=1x ./app/...
      - uses: golangci/golangci-lint-action@v9
        with:
          only-new-issues: true
